### ISSUE TITLE
Platform Installer should be versions or at least have a hashcode

### ISSUE THREAD

**Issue by Woland2k** [VirtoCommerce/vc-deploy-containers#2]
Hash code and version will allow to reference the exact version of installer to use thus removing unpredictable nature of latest image.

**Comment by mvktsk** [comment]
Task https://virtocommerce.atlassian.net/browse/VP-3580 has been created

**Comment by mvktsk** [comment]
fixed 
https://github.com/VirtoCommerce/vc-platform/pkgs/container/platform
